In [1]:
import sys
sys.path.append('/home/quant/qlib')
import pickle
import xqbutils as xqb
import pandas as pd
import os
import shutil
import subprocess
import logging
# 配置日志
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

threshold = 0.9
def get_stockinfo_wd():
    print('开始处理日行情数据')
    df = xqb.get_oracal_data(xqb.PRICES_CONFIG, 'ASHAREEODPRICES')
    df.rename(columns = {'S_INFO_WINDCODE':'STOCKCODE','TRADE_DT':'date','S_DQ_ADJOPEN':'OPEN','S_DQ_ADJHIGH':'HIGH','S_DQ_ADJLOW':'LOW','S_DQ_ADJCLOSE':'CLOSE','S_DQ_VOLUME':'VOLUME','S_DQ_AVGPRICE':'VWAP','S_DQ_ADJFACTOR':'FACTOR'}, inplace = True)
    df = df[['STOCKCODE','date','OPEN','HIGH','LOW','CLOSE','VOLUME','VWAP','FACTOR']]
    df['date'] = pd.to_datetime(df['date'])
    null_proportions = df.isnull().sum() / len(df)
    columns_to_drop = null_proportions[null_proportions > threshold].index
    df = df.drop(columns = columns_to_drop)
    df.set_index('date',inplace=True)
    df = df.sort_index()
    df = df['2014-01-01':]
    df.reset_index(drop=False, inplace=True)
    grouped = df.groupby('STOCKCODE')
    i = 0
    for name, group in grouped:
        group = group.drop(columns =['STOCKCODE'])
        group = group.sort_values(by='date', ascending=True)
        group.to_csv(f'/home/quant/qlib/stockinfo/{name}.csv',index=False)
        i += 1
        print(f'{i}:{name}')

def get_indexdaily():
    df = xqb.get_oracal_data(xqb.FACTOR_CONFIG,'JY_QY_INDEXDATA_CS')
    df = df.drop(columns=['ID','CREATETIME'])
    df.rename(columns = {'TRADEDATE':'date','TOPEN':'OPEN','THIGH':'HIGH','TLOW':'LOW','TCLOSE':'CLOSE'}, inplace = True)
    df['date'] = pd.to_datetime(df['date'])
    null_proportions = df.isnull().sum() / len(df)
    columns_to_drop = null_proportions[null_proportions > threshold].index
    df = df.drop(columns = columns_to_drop)
    df.set_index('date',inplace=True)
    df = df.sort_index()
    df = df['2014-01-01':]
    df.reset_index(drop=False, inplace=True)
    grouped = df.groupby('INDEXCODE')
    for name, group in grouped:
        group = group.drop(columns =['INDEXCODE'])
        group = group.sort_values(by='date', ascending=True)
        group.to_csv(f'/home/quant/qlib/indexinfo/{name}.ZS.csv',index=False)

# 公司股票池处理
def get_company_stock():
    column_names = ['SYMBOL', 'starttime', 'endtime']
    df_stock = pd.read_table("/home/quant/qlib_data/cn_data/instruments/all.txt", names=column_names)
    column_names = ['SYMBOL']
    df_company = pd.read_csv("/home/quant/qlib_data/section_codes.csv", names=column_names,dtype = str)
    result = df_stock[df_stock['SYMBOL'].str[:6].isin(df_company['SYMBOL'])]
    result.to_csv("/home/quant/qlib_data/cn_data/instruments/company.txt", sep='\t', index=False, header=False)


def get_csi300_stock():
    column_names = ['SYMBOL', 'starttime', 'endtime']
    df_stock = pd.read_table("/home/quant/qlib_data/cn_data/instruments/all.txt", names=column_names)
    df_company = pd.read_csv("/home/quant/qlib_data/csi300.csv", names=column_names)
    result = df_stock[df_stock['SYMBOL'].isin(df_company['SYMBOL'])]
    result.to_csv("/home/quant/qlib_data/cn_data/instruments/csi300.txt", sep='\t', index=False, header=False)

def save_data_company():
    """
    Saves the dataset to a pickle file.
    """
    import qlib
    from qlib.constant import REG_CN
    from qlib.utils import init_instance_by_config
    from datetime import datetime

    from qlib.data import D # 基础行情数据服务的对象
    provider_uri = "/home/quant/qlib_data/cn_data"

    #数据初始化，
    qlib.init(provider_uri=provider_uri, region=REG_CN) # 初始化

    stockpool =  D.instruments(market='company')

    end_time = datetime.now().strftime("%Y-%m-%d")
    print(f"今天的日期是: {end_time}")

    data_handler_config = {
        "start_time": "2008-01-01",
        "end_time": end_time,
        "fit_start_time": "2008-01-01",
        "fit_end_time": "2021-12-31",
        "instruments": stockpool,
        "infer_processors":[
            {"class": "RobustZScoreNorm",
              "kwargs":{
                  "fields_group": "feature",
                  "clip_outlier": "true"
              }
             },
            {"class": "Fillna",
              "kwargs":{
                  "fields_group": "feature"
              }
             },
        ],
        "label": [["Ref($close, -2) / Ref($close, -1) - 1"], ["LABEL0"]]
    }

    task = {
        "dataset": {  #　因子数据集参数配置
            # 数据集类，是Dataset with Data(H)andler的缩写，即带数据处理器的数据集
            "class": "TSDatasetH",
            "module_path": "qlib.data.dataset",
            "kwargs": {
                "handler": { # 数据集使用的数据处理器配置
                    "class": "AlphaTa", # 数据处理器类，继承自DataHandlerLP
                    "module_path": "qlib.contrib.data.handler_xie", # 数据处理器类所在模块
                    "kwargs": data_handler_config, # 数据处理器参数配置
                },
                "segments": {
                    "train": ("2008-01-01", "2021-12-31"),
                    "valid": ("2022-01-01", "2023-12-31"),
                    "test": ("2024-01-01", end_time),
                },
                "step_len": 20,  # 数据集步长
            },
        },
    }

    dataset_ts = init_instance_by_config(task["dataset"]) # 类型DatasetH
    dataset_ts.config(dump_all=True, recursive=True)
    dataset_ts.to_pickle(path="dataset_ts.pkl", dump_all=True)

    task = {
        "dataset": {  #　因子数据集参数配置
            # 数据集类，是Dataset with Data(H)andler的缩写，即带数据处理器的数据集
            "class": "DatasetH",
            "module_path": "qlib.data.dataset",
            "kwargs": {
                "handler": { # 数据集使用的数据处理器配置
                    "class": "AlphaTa", # 数据处理器类，继承自DataHandlerLP
                    "module_path": "qlib.contrib.data.handler_xie", # 数据处理器类所在模块
                    "kwargs": data_handler_config, # 数据处理器参数配置
                },
                "segments": {
                    "train": ("2008-01-01", "2021-12-31"),
                    "valid": ("2022-01-01", "2023-12-31"),
                    "test": ("2024-01-01", end_time),
                },
            },
        },
    }
    # 实例化数据集，从基础行情数据计算出的包含所有特征（因子）和标签值的数据集。
    dataset = init_instance_by_config(task["dataset"]) # 类型DatasetH
    dataset.config(dump_all=True, recursive=True)
    dataset.to_pickle(path="dataset.pkl", dump_all=True)


def save_data_all():
    """
    Saves the dataset to a pickle file.
    """
    import qlib
    from qlib.constant import REG_CN
    from qlib.utils import init_instance_by_config
    from datetime import datetime

    from qlib.data import D # 基础行情数据服务的对象
    provider_uri = "/home/quant/qlib_data/cn_data"

    #数据初始化，
    qlib.init(provider_uri=provider_uri, region=REG_CN) # 初始化

    stockpool =  D.instruments(market='all')

    end_time = datetime.now().strftime("%Y-%m-%d")
    print(f"今天的日期是: {end_time}")

    data_handler_config = {
        "start_time": "2014-01-01",
        "end_time": end_time,
        "fit_start_time": "2014-01-01",
        "fit_end_time": "2021-12-31",
        "instruments": stockpool,
        "infer_processors":[
            {"class": "RobustZScoreNorm",
              "kwargs":{
                  "fields_group": "feature",
                  "clip_outlier": "true"
              }
             },
            {"class": "Fillna",
              "kwargs":{
                  "fields_group": "feature"
              }
             },
        ],
        "label": [["Ref($close, -2) / Ref($close, -1) - 1"], ["LABEL0"]]
    }

    # task = {
    #     "dataset": {  #　因子数据集参数配置
    #         # 数据集类，是Dataset with Data(H)andler的缩写，即带数据处理器的数据集
    #         "class": "TSDatasetH",
    #         "module_path": "qlib.data.dataset",
    #         "kwargs": {
    #             "handler": { # 数据集使用的数据处理器配置
    #                 "class": "AlphaTa", # 数据处理器类，继承自DataHandlerLP
    #                 "module_path": "qlib.contrib.data.handler_xie", # 数据处理器类所在模块
    #                 "kwargs": data_handler_config, # 数据处理器参数配置
    #             },
    #             "segments": {
    #                 "train": ("2014-01-01", "2021-12-31"),
    #                 "valid": ("2022-01-01", "2023-12-31"),
    #                 "test": ("2024-01-01", end_time),
    #             },
    #             "step_len": 20,  # 数据集步长
    #         },
    #     },
    # }
    #
    # dataset_ts = init_instance_by_config(task["dataset"]) # 类型DatasetH
    # dataset_ts.config(dump_all=True, recursive=True)
    # dataset_ts.to_pickle(path="dataset_ts_all.pkl", dump_all=True)

    task = {
        "dataset": {  #　因子数据集参数配置
            # 数据集类，是Dataset with Data(H)andler的缩写，即带数据处理器的数据集
            "class": "DatasetH",
            "module_path": "qlib.data.dataset",
            "kwargs": {
                "handler": { # 数据集使用的数据处理器配置
                    "class": "AlphaTa", # 数据处理器类，继承自DataHandlerLP
                    "module_path": "qlib.contrib.data.handler_xie", # 数据处理器类所在模块
                    "kwargs": data_handler_config, # 数据处理器参数配置
                },
                "segments": {
                    "train": ("2014-01-01", "2021-12-31"),
                    "valid": ("2022-01-01", "2023-12-31"),
                    "test": ("2024-01-01", end_time),
                },
            },
        },
    }
    # 实例化数据集，从基础行情数据计算出的包含所有特征（因子）和标签值的数据集。
    dataset = init_instance_by_config(task["dataset"]) # 类型DatasetH
    dataset.config(dump_all=True, recursive=True)
    dataset.to_pickle(path="/home/quant/qlib/dataset_all.pkl", dump_all=True)


def load_data(is_ts):
    """
    Loads the dataset from the pickle file.
    """
    if is_ts:
        with open("/home/quant/qlib/dataset_ts.pkl", "rb") as file_dataset:
            dataset = pickle.load(file_dataset)
        return dataset
    else:
        with open("/home/quant/qlib/dataset.pkl", "rb") as file_dataset:
            dataset = pickle.load(file_dataset)
        return dataset

def load_data_all(is_ts):
    """
    Loads the dataset from the pickle file.
    """
    if is_ts:
        with open("/home/quant/qlib/dataset_ts_all.pkl", "rb") as file_dataset:
            dataset = pickle.load(file_dataset)
        return dataset
    else:
        with open("/home/quant/qlib/dataset_all.pkl", "rb") as file_dataset:
            dataset = pickle.load(file_dataset)
        return dataset

def load_model(model_name):
    """
    Loads the model from the pickle file.
    """
    model_name = "/home/quant/qlib/saved_models/" + model_name + ".pkl"
    with open(model_name, "rb") as file_model:
        model = pickle.load(file_model)
    return model

def get_pred_scores(modelname, is_ts):
    """
    Gets the predictions and scores from the model.
    """
    model = load_model(modelname)
    if "_all" in modelname:
        dataset = load_data_all(is_ts)
    else:
        dataset = load_data(is_ts)
    pred_score = model.predict(dataset)
    pred_score = pred_score.rename('score')
    pred_score = pred_score.to_frame('score')
    last_date = pred_score.index.get_level_values('datetime').max()

    # 提取最后一天的所有股票数据
    last_day_scores = pred_score.xs(last_date, level='datetime')
    last_day_scores = last_day_scores.reset_index()

    # # 按 score 降序排序并取前100
    # top_100 = last_day_scores.sort_values('score', ascending=False).head(100)
    #
    # # 重置索引（可选，如果希望 instrument 变成列）
    # top_100 = top_100.reset_index()

    return last_day_scores

def get_pred_scores_mix():
    """
    Gets the predictions and scores from the model.
    """
    w_gru = 0.3
    w_moe = 0.3
    w_lgb = 0.4

    dataset_ts = load_data(True)
    dataset = load_data(False)

    model = load_model("gru_company")
    pred_score_gru = model.predict(dataset_ts)
    pred_score_gru = pred_score_gru.rename('score')
    pred_score_gru = pred_score_gru.to_frame('score')
    last_date = pred_score_gru.index.get_level_values('datetime').max()
    last_day_scores_gru = pred_score_gru.xs(last_date, level='datetime')
    last_day_scores_gru = last_day_scores_gru.reset_index()

    model = load_model("moe_company")
    pred_score_moe = model.predict(dataset_ts)
    pred_score_moe = pred_score_moe.rename('score')
    pred_score_moe = pred_score_moe.to_frame('score')
    last_date = pred_score_moe.index.get_level_values('datetime').max()
    last_day_scores_moe = pred_score_moe.xs(last_date, level='datetime')
    last_day_scores_moe = last_day_scores_moe.reset_index()

    model = load_model("lgb_company")
    pred_score_lgb = model.predict(dataset)
    pred_score_lgb = pred_score_lgb.rename('score')
    pred_score_lgb = pred_score_lgb.to_frame('score')
    last_date = pred_score_lgb.index.get_level_values('datetime').max()
    last_day_scores_lgb = pred_score_lgb.xs(last_date, level='datetime')
    last_day_scores_lgb = last_day_scores_lgb.reset_index()

    # 合并三个 DataFrame
    merged_df = pd.merge(
        last_day_scores_gru,
        last_day_scores_moe,
        on="instrument",
        suffixes=("_gru", "_moe")
    )
    merged_df = pd.merge(
        merged_df,
        last_day_scores_lgb,
        on="instrument"
    )

    # 计算加权平均 score
    merged_df["score"] = (
        merged_df["score_gru"] * w_gru +
        merged_df["score_moe"] * w_moe +
        merged_df["score"] * w_lgb  # 注意：这里的 score 是 lgb 的列
    )

    # 只保留 instrument 和最终 score
    final_scores = merged_df[["instrument", "score"]]

    return final_scores

def delete_files_in_folder(folder_path):
    """
    删除指定文件夹下的所有文件和子文件夹

    参数:
        folder_path (str): 要清空的文件夹路径
    """
    try:
        # 检查文件夹是否存在
        if not os.path.exists(folder_path):
            print(f"文件夹 {folder_path} 不存在")
            return

        # 遍历文件夹
        for filename in os.listdir(folder_path):
            file_path = os.path.join(folder_path, filename)

            try:
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)  # 删除文件或链接
                elif os.path.isdir(file_path):
                    shutil.rmtree(file_path)  # 删除子文件夹及其内容
            except Exception as e:
                print(f"删除 {file_path} 失败. 原因: {e}")

        print(f"已成功清空文件夹 {folder_path}")
    except Exception as e:
        print(f"处理文件夹 {folder_path} 时出错. 原因: {e}")

def clean_data():
    delete_files_in_folder('/home/quant/qlib/stockinfo')
    delete_files_in_folder('/home/quant/qlib/indexinfo')
    delete_files_in_folder('/home/quant/qlib_data/cn_data')


def run_dump_bin_script_index():
    """
    执行指定的Python脚本命令
    """
    command = [
        sys.executable,  # 使用当前Python解释器
        "/home/quant/qlib/scripts/dump_bin.py",
        "dump_all",
        "--csv_path", "/home/quant/qlib/indexinfo/",
        "--qlib_dir", "/home/quant/qlib_data/cn_data"
    ]

    try:
        # 执行命令并捕获输出
        result = subprocess.run(
            command,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        print(result.stdout)

        if result.stderr:
            print("错误信息：")
            print(result.stderr)

        return True
    except subprocess.CalledProcessError as e:
        print(f"命令执行失败，返回码：{e.returncode}")
        print("错误输出：")
        print(e.stderr)
        return False

def run_dump_bin_script_stock():
    """
    执行指定的Python脚本命令
    """
    command = [
        sys.executable,  # 使用当前Python解释器
        "/home/quant/qlib/scripts/dump_bin.py",
        "dump_all",
        "--csv_path", "/home/quant/qlib/stockinfo/",
        "--qlib_dir", "/home/quant/qlib_data/cn_data"
    ]

    try:
        # 执行命令并捕获输出
        result = subprocess.run(
            command,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        print(result.stdout)

        if result.stderr:
            print("错误信息：")
            print(result.stderr)

        return True
    except subprocess.CalledProcessError as e:
        print(f"命令执行失败，返回码：{e.returncode}")
        print("错误输出：")
        print(e.stderr)
        return False

def get_orders(holding_stocks,last_day_scores):
    sell_stocks =[]
    buy_stocks = []
    #计算当前持仓不在预测股票列表中的股票（主要是不在公司股票池的情况）

    # 计算2个股票的交集
    common_elements = list(set(holding_stocks) & set(last_day_scores['instrument'].tolist()))
    # 计算不在股票池的股票
    difference = list(set(holding_stocks) - set(common_elements))
    # 存在不在股票池的股票
    difference_length = len(difference)
    # append使用错误.....
    sell_stocks = sell_stocks.append( difference)
    if difference_length > 4:
        sell_stocks = sell_stocks[:4]
    else:
        valid_codes = [code for code in holding_stocks if code in last_day_scores['instrument'].values]
        sorted_df = last_day_scores[last_day_scores['instrument'].isin(valid_codes)].sort_values(
            by='score',
            ascending=True
        ).reset_index(drop=True)
        sell_stocks = sell_stocks.append(sorted_df['instrument'][:4 - difference_length].tolist())

    top_100 = last_day_scores.sort_values('score', ascending=False).head(100)

    # 重置索引（可选，如果希望 instrument 变成列）
    top_100 = top_100.reset_index()
    filtered_top_100 = top_100[~top_100['instrument'].isin(sorted_df['instrument'])]
    buy_stocks = buy_stocks.append(filtered_top_100['instrument'].tolist()[:4])
    return sell_stocks,buy_stocks

def get_orders_n(holding_stocks, last_day_scores):
    # 初始化买卖股票列表
    sell_stocks = []
    buy_stocks = []

    # ===== 卖出逻辑 =====
    # 当前持有的股票中，哪些在预测列表中（即 last_day_scores 中的 instrument）
    holding_set = set(holding_stocks)
    pred_instruments = set(last_day_scores['instrument'].tolist())

    # 当前持仓中，不在预测列表中的股票 -> 可能要卖出
    not_in_pred = list(holding_set - pred_instruments)
    not_in_pred_length = len(not_in_pred)

    # 如果不在预测池中的持仓股票超过4个，只卖前4个（这里直接取前4个或者全部？目前取全部然后截断）
    if not_in_pred_length > 4:
        sell_stocks = not_in_pred[:4]  # 只卖前4个
    else:
        sell_stocks = not_in_pred[:]  # 先卖所有不在预测池中的持仓
        # 如果还有剩余卖出名额，从【预测池中的持仓】里，得分低的股票中补充卖出
        remaining_to_sell = 4 - not_in_pred_length

        if remaining_to_sell > 0:
            # 当前持仓中，且在预测池中的股票
            valid_codes = [code for code in holding_stocks if code in pred_instruments]
            # 找出这些股票在 last_day_scores 中的得分，并按得分升序（得分低的可能表现不好）
            sorted_holding_in_pred = last_day_scores[
                last_day_scores['instrument'].isin(valid_codes)
            ].sort_values(by='score', ascending=True).reset_index(drop=True)

            # 补充卖出得分最低的 remaining_to_sell 只
            sell_stocks.extend(sorted_holding_in_pred['instrument'].head(remaining_to_sell).tolist())

    # ===== 买入逻辑 =====
    # 取得分最高的前 100 只股票
    top_100 = last_day_scores.sort_values(by='score', ascending=False).head(100)
    top_100_instruments = set(top_100['instrument'].tolist())

    # 假设我们不想重复买已经持仓的股票（或者根据某些策略排除）
    # 这里简单起见：从 top_100 中排除当前已经持仓的股票
    available_to_buy = top_100[~top_100['instrument'].isin(holding_stocks)].reset_index(drop=True)

    # 买入得分最高的前 4 只（未被持仓的）
    buy_stocks = available_to_buy['instrument'].head(4).tolist()

    return sell_stocks, buy_stocks

# 获取300指数当前列表
def get_csi300():
    column_names = ['SYMBOL', 'starttime', 'endtime']
    df_csi300 = pd.read_csv("/home/quant/qlib_data/csi300.csv", names=column_names)
    return df_csi300['SYMBOL'].tolist()

# 计算持仓中csi300指数股的个数
def get_csi300_num(holding_stocks):
    return len(set(holding_stocks) & set(get_csi300()))

# 计算需要卖出的指数股个数和买入的指数股个数,指数为60%，30个
def get_csi300_orders_num(holding_stocks,target = 30):
    csi300_num = get_csi300_num(holding_stocks)
    diff = target - csi300_num
    if diff > 0:
        return diff, 0
    elif diff < 0:
        return 0, -diff
    else:
        return 3, 3

# 计算指数外股票买卖数量
def get_out_csi300_orders_num(holding_stocks,target = 50):
    # 计算需要买卖的指数股数量
    csi300_buy_num, csi300_sell_num = get_csi300_orders_num(holding_stocks)
    # hold_num = len(holding_stocks) - target
    #持仓超过50只
    #持仓低于50只
    #持仓为50只，当前只处理了刚好50只
    out_buy_num = 0
    out_sell_num = 0
    if csi300_buy_num == csi300_sell_num:
        out_buy_num = 2
        out_sell_num = 2
    elif csi300_buy_num > csi300_sell_num:
        out_buy_num = 0
        out_sell_num = csi300_buy_num
    else:
        out_buy_num = csi300_sell_num
        out_sell_num = 0
    return out_buy_num, out_sell_num

"""
当前持仓中，指数的排序，卖出倒数三只指数股
计算所有指数排序，计算持仓外指数排名，买入前3名
当前只处理公司股票池
"""
def proces_csi300_stock(holding_stocks,last_day_scores):

    csi300_buy_num, csi300_sell_num = get_csi300_orders_num(holding_stocks)
    out_buy_num, out_sell_num = get_out_csi300_orders_num(holding_stocks)

    csi300 = get_csi300()

    holding_set = set(holding_stocks)
    # 持仓中的指数股
    in_300 = list(holding_set & set(csi300))
    # 未持仓的指数股
    left_300 = list(set(csi300) - set(in_300))

    # 持仓中的非指数股
    out_300 = list(holding_set - set(in_300))
    # 未持仓的非指数股,所有股票-300 - 已持有的非300
    left_out_300 = list(set(last_day_scores['instrument'].to_list()) - set(csi300) - set(out_300))


    #持仓的指数股排序，由低到高
    sorted_holding_in_csi300 = last_day_scores[
                last_day_scores['instrument'].isin(in_300)
            ].sort_values(by='score', ascending=True).reset_index(drop=True)

    #持仓中非指数股的排序,，由低到高
    sorted_holding_out_csi300 = last_day_scores[
                last_day_scores['instrument'].isin(out_300)
            ].sort_values(by='score', ascending=True).reset_index(drop=True)

    # 未持仓的指数股排序，从高到底
    sorted_left_300 = last_day_scores[
                last_day_scores['instrument'].isin(left_300)
            ].sort_values(by='score', ascending=False).reset_index(drop=True)

    # 未持仓的非指数股排序，从高到底
    sorted_left_out_300 = last_day_scores[
                last_day_scores['instrument'].isin(left_out_300)
            ].sort_values(by='score', ascending=False).reset_index(drop=True)

def get_trade_stock(hold_stock_list,perd_scord):
    # 输入：持仓的股票列表，预测的得分列表，账户余额
    # 输出：卖出的股票列表，买入的股票列表,sell_list,buy_list
    # 约束：1、买卖数量限制 2、优先卖出不是股票池的股票（perd_scord中的股票即为股票池）3、指数股数量约束4、行业约束（行业占比？条件是什么）
    # 5、去掉连续涨停的股票（预测前n天，n>=2，不同的交易所涨跌幅不一样,或者最近2天涨幅超过19.5%，或者最近3天涨幅超过29%的)
    # 6、持有时间的约束（至少持有N天）7、市值的约束（市值低于50亿的股票不能超过N只）

    # 股票池本身约束
    # 1、ST的约束
    # 2、新股约束


    """
    1、约束
    买卖数量限制/优先卖出不是股票池的股票/指数股数量约束/行业约束/持有时间的约束(至少持有N天)/市值的约束(市值低于M亿的股票不能超过N只)/连续涨跌停约束

    2、回测
    输入：预测分数/账户余额(回测一般为一个亿)/约束（多条件约束如何传入）
    输出：回测相关指标

    3、预测
    输入：现有持仓/预测分数/账户余额/约束（多条件约束如何传入）
    输出：卖出列表，买入列表
    """


    pass

In [3]:
# 初始化环境，每天只需执行一次
# 删除历史数据、获取最新行情数据、整理成qlib格式文件、生成数据文件
clean_data()
get_indexdaily()
get_stockinfo_wd()
run_dump_bin_script_index()
run_dump_bin_script_stock()
get_company_stock()
get_csi300_stock()
save_data_company()
# save_data_all()

已成功清空文件夹 /home/quant/qlib/stockinfo
已成功清空文件夹 /home/quant/qlib/indexinfo
已成功清空文件夹 /home/quant/qlib_data/cn_data
开始处理日行情数据
1:000001.SZ
2:000002.SZ
3:000004.SZ
4:000005.SZ
5:000006.SZ
6:000007.SZ
7:000008.SZ
8:000009.SZ
9:000010.SZ
10:000011.SZ
11:000012.SZ
12:000014.SZ
13:000016.SZ
14:000017.SZ
15:000018.SZ
16:000019.SZ
17:000020.SZ
18:000021.SZ
19:000023.SZ
20:000024.SZ
21:000025.SZ
22:000026.SZ
23:000027.SZ
24:000028.SZ
25:000029.SZ
26:000030.SZ
27:000031.SZ
28:000032.SZ
29:000033.SZ
30:000034.SZ
31:000035.SZ
32:000036.SZ
33:000037.SZ
34:000038.SZ
35:000039.SZ
36:000040.SZ
37:000042.SZ
38:000045.SZ
39:000046.SZ
40:000048.SZ
41:000049.SZ
42:000050.SZ
43:000055.SZ
44:000056.SZ
45:000058.SZ
46:000059.SZ
47:000060.SZ
48:000061.SZ
49:000062.SZ
50:000063.SZ
51:000065.SZ
52:000066.SZ
53:000068.SZ
54:000069.SZ
55:000070.SZ
56:000078.SZ
57:000088.SZ
58:000089.SZ
59:000090.SZ
60:000096.SZ
61:000099.SZ
62:000100.SZ
63:000150.SZ
64:000151.SZ
65:000153.SZ
66:000155.SZ
67:000156.SZ
68:000157.SZ
69:000158.SZ
70:000159.SZ
71:000166.SZ
72:000301.SZ
73:000333.SZ
74:000338.SZ
75:000400.SZ
76:000401.SZ
77:000402.SZ
78:000403.SZ
79:000404.SZ
80:000407.SZ
81:000408.SZ
82:000409.SZ
83:000410.SZ
84:000411.SZ
85:000413.SZ
86:000415.SZ
87:000416.SZ
88:000417.SZ
89:000418.SZ
90:000419.SZ
91:000420.SZ
92:000421.SZ
93:000422.SZ
94:000423.SZ
95:000425.SZ
96:000426.SZ
97:000428.SZ
98:000429.SZ
99:000430.SZ
100:000488.SZ
101:000498.SZ
102:000501.SZ
103:000502.SZ
104:000503.SZ
105:000504.SZ
106:000505.SZ
107:000506.SZ
108:000507.SZ
109:000509.SZ
110:000510.SZ
111:000511.SZ
112:000513.SZ
113:000514.SZ
114:000516.SZ
115:000517.SZ
116:000518.SZ
117:000519.SZ
118:000520.SZ
119:000521.SZ
120:000523.SZ
121:000524.SZ
122:000525.SZ
123:000526.SZ
124:000528.SZ
125:000529.SZ
126:000530.SZ
127:000531.SZ
128:000532.SZ
129:000533.SZ
130:000534.SZ
131:000536.SZ
132:000537.SZ
133:000538.SZ
134:000539.SZ
135:000540.SZ
136:000541.SZ
137:000543.SZ
138:000544.SZ
139:000545.SZ
140:000546.SZ
141:000547.SZ
142:000548.SZ
143:000550.SZ
144:000551.SZ
145:000552.SZ
146:000553.SZ
147:000554.SZ
148:000555.SZ
149:000557.SZ
150:000558.SZ
151:000559.SZ
152:000560.SZ
153:000561.SZ
154:000562.SZ
155:000563.SZ
156:000564.SZ
157:000565.SZ
158:000566.SZ
159:000567.SZ
160:000568.SZ
161:000570.SZ
162:000571.SZ
163:000572.SZ
164:000573.SZ
165:000576.SZ
166:000581.SZ
167:000582.SZ
168:000584.SZ
169:000585.SZ
170:000586.SZ
171:000587.SZ
172:000589.SZ
173:000590.SZ
174:000591.SZ
175:000592.SZ
176:000593.SZ
177:000594.SZ
178:000595.SZ
179:000596.SZ
180:000597.SZ
181:000598.SZ
182:000599.SZ
183:000600.SZ
184:000601.SZ
185:000603.SZ
186:000605.SZ
187:000606.SZ
188:000607.SZ
189:000608.SZ
190:000609.SZ
191:000610.SZ
192:000611.SZ
193:000612.SZ
194:000613.SZ
195:000615.SZ
196:000616.SZ
197:000617.SZ
198:000619.SZ
199:000620.SZ
200:000622.SZ
201:000623.SZ
202:000625.SZ
203:000626.SZ
204:000627.SZ
205:000628.SZ
206:000629.SZ
207:000630.SZ
208:000631.SZ
209:000632.SZ
210:000633.SZ
211:000635.SZ
212:000636.SZ
213:000637.SZ
214:000638.SZ
215:000639.SZ
216:000650.SZ
217:000651.SZ
218:000652.SZ
219:000655.SZ
220:000656.SZ
221:000657.SZ
222:000659.SZ
223:000661.SZ
224:000662.SZ
225:000663.SZ
226:000665.SZ
227:000666.SZ
228:000667.SZ
229:000668.SZ
230:000669.SZ
231:000670.SZ
232:000671.SZ
233:000672.SZ
234:000673.SZ
235:000676.SZ
236:000677.SZ
237:000678.SZ
238:000679.SZ
239:000680.SZ
240:000681.SZ
241:000682.SZ
242:000683.SZ
243:000685.SZ
244:000686.SZ
245:000687.SZ
246:000688.SZ
247:000690.SZ
248:000691.SZ
249:000692.SZ
250:000693.SZ
251:000695.SZ
252:000697.SZ
253:000698.SZ
254:000700.SZ
255:000701.SZ
256:000702.SZ
257:000703.SZ
258:000705.SZ
259:000707.SZ
260:000708.SZ
261:000709.SZ
262:000710.SZ
263:000711.SZ
264:000712.SZ
265:000713.SZ
266:000715.SZ
267:000716.SZ
268:000717.SZ
269:000718.SZ
270:000719.SZ
271:000720.SZ
272:000721.SZ
273:000722.SZ
274:000723.SZ
275:000725.SZ
276:000726.SZ
277:000727.SZ
278:000728.SZ
279:000729.SZ
280:000731.SZ
281:000732.SZ
282:000733.SZ
283:000735.SZ
284:000736.SZ
285:000737.SZ
286:000738.SZ
287:000739.SZ
288:000748.SZ
289:000750.SZ
290:000751.SZ
291:000752.SZ
292:000753.SZ
293:000755.SZ
294:000756.SZ
295:000757.SZ
296:000758.SZ
297:000759.SZ
298:000760.SZ
299:000761.SZ
300:000762.SZ
301:000766.SZ
302:000767.SZ
303:000768.SZ
304:000776.SZ
305:000777.SZ
306:000778.SZ
307:000779.SZ
308:000780.SZ
309:000782.SZ
310:000783.SZ
311:000785.SZ
312:000786.SZ
313:000788.SZ
314:000789.SZ
315:000790.SZ
316:000791.SZ
317:000792.SZ
318:000793.SZ
319:000795.SZ
320:000796.SZ
321:000797.SZ
322:000798.SZ
323:000799.SZ
324:000800.SZ
325:000801.SZ
326:000802.SZ
327:000803.SZ
328:000806.SZ
329:000807.SZ
330:000809.SZ
331:000810.SZ
332:000811.SZ
333:000812.SZ
334:000813.SZ
335:000815.SZ
336:000816.SZ
337:000818.SZ
338:000819.SZ
339:000820.SZ
340:000821.SZ
341:000822.SZ
342:000823.SZ
343:000825.SZ
344:000826.SZ
345:000828.SZ
346:000829.SZ
347:000830.SZ
348:000831.SZ
349:000833.SZ
350:000835.SZ
351:000836.SZ
352:000837.SZ
353:000838.SZ
354:000839.SZ
355:000848.SZ
356:000850.SZ
357:000851.SZ
358:000852.SZ
359:000856.SZ
360:000858.SZ
361:000859.SZ
362:000860.SZ
363:000861.SZ
364:000862.SZ
365:000863.SZ
366:000868.SZ
367:000869.SZ
368:000875.SZ
369:000876.SZ
370:000877.SZ
371:000878.SZ
372:000880.SZ
373:000881.SZ
374:000882.SZ
375:000883.SZ
376:000885.SZ
377:000886.SZ
378:000887.SZ
379:000888.SZ
380:000889.SZ
381:000890.SZ
382:000892.SZ
383:000893.SZ
384:000895.SZ
385:000897.SZ
386:000898.SZ
387:000899.SZ
388:000900.SZ
389:000901.SZ
390:000902.SZ
391:000903.SZ
392:000905.SZ
393:000906.SZ
394:000908.SZ
395:000909.SZ
396:000910.SZ
397:000911.SZ
398:000912.SZ
399:000913.SZ
400:000915.SZ
401:000916.SZ
402:000917.SZ
403:000918.SZ
404:000919.SZ
405:000920.SZ
406:000921.SZ
407:000922.SZ
408:000923.SZ
409:000925.SZ
410:000926.SZ
411:000927.SZ
412:000928.SZ
413:000929.SZ
414:000930.SZ
415:000931.SZ
416:000932.SZ
417:000933.SZ
418:000935.SZ
419:000936.SZ
420:000937.SZ
421:000938.SZ
422:000939.SZ
423:000948.SZ
424:000949.SZ
425:000950.SZ
426:000951.SZ
427:000952.SZ
428:000953.SZ
429:000955.SZ
430:000957.SZ
431:000958.SZ
432:000959.SZ
433:000960.SZ
434:000961.SZ
435:000962.SZ
436:000963.SZ
437:000965.SZ
438:000966.SZ
439:000967.SZ
440:000968.SZ
441:000969.SZ
442:000970.SZ
443:000971.SZ
444:000972.SZ
445:000973.SZ
446:000975.SZ
447:000976.SZ
448:000977.SZ
449:000978.SZ
450:000979.SZ
451:000980.SZ
452:000981.SZ
453:000982.SZ
454:000983.SZ
455:000985.SZ
456:000987.SZ
457:000988.SZ
458:000989.SZ
459:000990.SZ
460:000993.SZ
461:000995.SZ
462:000996.SZ
463:000997.SZ
464:000998.SZ
465:000999.SZ
466:001201.SZ
467:001202.SZ
468:001203.SZ
469:001205.SZ
470:001206.SZ
471:001207.SZ
472:001208.SZ
473:001209.SZ
474:001210.SZ
475:001211.SZ
476:001212.SZ
477:001213.SZ
478:001215.SZ
479:001216.SZ
480:001217.SZ
481:001218.SZ
482:001219.SZ
483:001221.SZ
484:001222.SZ
485:001223.SZ
486:001225.SZ
487:001226.SZ
488:001227.SZ
489:001228.SZ
490:001229.SZ
491:001230.SZ
492:001231.SZ
493:001234.SZ
494:001236.SZ
495:001238.SZ
496:001239.SZ
497:001255.SZ
498:001256.SZ
499:001258.SZ
500:001259.SZ
501:001260.SZ
502:001266.SZ
503:001267.SZ
504:001268.SZ
505:001269.SZ
506:001270.SZ
507:001277.SZ
508:001278.SZ
509:001279.SZ
510:001282.SZ
511:001283.SZ
512:001286.SZ
513:001287.SZ
514:001288.SZ
515:001289.SZ
516:001296.SZ
517:001298.SZ
518:001299.SZ
519:001300.SZ
520:001301.SZ
521:001306.SZ
522:001308.SZ
523:001309.SZ
524:001311.SZ
525:001313.SZ
526:001314.SZ
527:001316.SZ
528:001317.SZ
529:001318.SZ
530:001319.SZ
531:001322.SZ
532:001323.SZ
533:001324.SZ
534:001326.SZ
535:001328.SZ
536:001330.SZ
537:001331.SZ
538:001332.SZ
539:001333.SZ
540:001335.SZ
541:001336.SZ
542:001337.SZ
543:001338.SZ
544:001339.SZ
545:001356.SZ
546:001358.SZ
547:001359.SZ
548:001360.SZ
549:001366.SZ
550:001367.SZ
551:001368.SZ
552:001373.SZ
553:001376.SZ
554:001378.SZ
555:001379.SZ
556:001380.SZ
557:001382.SZ
558:001387.SZ
559:001388.SZ
560:001389.SZ
561:001390.SZ
562:001391.SZ
563:001395.SZ
564:001400.SZ
565:001696.SZ
566:001872.SZ
567:001896.SZ
568:001914.SZ
569:001965.SZ
570:001979.SZ
571:002001.SZ
572:002002.SZ
573:002003.SZ
574:002004.SZ
575:002005.SZ
576:002006.SZ
577:002007.SZ
578:002008.SZ
579:002009.SZ
580:002010.SZ
581:002011.SZ
582:002012.SZ
583:002013.SZ
584:002014.SZ
585:002015.SZ
586:002016.SZ
587:002017.SZ
588:002018.SZ
589:002019.SZ
590:002020.SZ
591:002021.SZ
592:002022.SZ
593:002023.SZ
594:002024.SZ
595:002025.SZ
596:002026.SZ
597:002027.SZ
598:002028.SZ
599:002029.SZ
600:002030.SZ
601:002031.SZ
602:002032.SZ
603:002033.SZ
604:002034.SZ
605:002035.SZ
606:002036.SZ
607:002037.SZ
608:002038.SZ
609:002039.SZ
610:002040.SZ
611:002041.SZ
612:002042.SZ
613:002043.SZ
614:002044.SZ
615:002045.SZ
616:002046.SZ
617:002047.SZ
618:002048.SZ
619:002049.SZ
620:002050.SZ
621:002051.SZ
622:002052.SZ
623:002053.SZ
624:002054.SZ
625:002055.SZ
626:002056.SZ
627:002057.SZ
628:002058.SZ
629:002059.SZ
630:002060.SZ
631:002061.SZ
632:002062.SZ
633:002063.SZ
634:002064.SZ
635:002065.SZ
636:002066.SZ
637:002067.SZ
638:002068.SZ
639:002069.SZ
640:002070.SZ
641:002071.SZ
642:002072.SZ
643:002073.SZ
644:002074.SZ
645:002075.SZ
646:002076.SZ
647:002077.SZ
648:002078.SZ
649:002079.SZ
650:002080.SZ
651:002081.SZ
652:002082.SZ
653:002083.SZ
654:002084.SZ
655:002085.SZ
656:002086.SZ
657:002087.SZ
658:002088.SZ
659:002089.SZ
660:002090.SZ
661:002091.SZ
662:002092.SZ
663:002093.SZ
664:002094.SZ
665:002095.SZ
666:002096.SZ
667:002097.SZ
668:002098.SZ
669:002099.SZ
670:002100.SZ
671:002101.SZ
672:002102.SZ
673:002103.SZ
674:002104.SZ
675:002105.SZ
676:002106.SZ
677:002107.SZ
678:002108.SZ
679:002109.SZ
680:002110.SZ
681:002111.SZ
682:002112.SZ
683:002113.SZ
684:002114.SZ
685:002115.SZ
686:002116.SZ
687:002117.SZ
688:002118.SZ
689:002119.SZ
690:002120.SZ
691:002121.SZ
692:002122.SZ
693:002123.SZ
694:002124.SZ
695:002125.SZ
696:002126.SZ
697:002127.SZ
698:002128.SZ
699:002129.SZ
700:002130.SZ
701:002131.SZ
702:002132.SZ
703:002133.SZ
704:002134.SZ
705:002135.SZ
706:002136.SZ
707:002137.SZ
708:002138.SZ
709:002139.SZ
710:002140.SZ
711:002141.SZ
712:002142.SZ
713:002143.SZ
714:002144.SZ
715:002145.SZ
716:002146.SZ
717:002147.SZ
718:002148.SZ
719:002149.SZ
720:002150.SZ
721:002151.SZ
722:002152.SZ
723:002153.SZ
724:002154.SZ
725:002155.SZ
726:002156.SZ
727:002157.SZ
728:002158.SZ
729:002159.SZ
730:002160.SZ
731:002161.SZ
732:002162.SZ
733:002163.SZ
734:002164.SZ
735:002165.SZ
736:002166.SZ
737:002167.SZ
738:002168.SZ
739:002169.SZ
740:002170.SZ
741:002171.SZ
742:002172.SZ
743:002173.SZ
744:002174.SZ
745:002175.SZ
746:002176.SZ
747:002177.SZ
748:002178.SZ
749:002179.SZ
750:002180.SZ
751:002181.SZ
752:002182.SZ
753:002183.SZ
754:002184.SZ
755:002185.SZ
756:002186.SZ
757:002187.SZ
758:002188.SZ
759:002189.SZ
760:002190.SZ
761:002191.SZ
762:002192.SZ
763:002193.SZ
764:002194.SZ
765:002195.SZ
766:002196.SZ
767:002197.SZ
768:002198.SZ
769:002199.SZ
770:002200.SZ
771:002201.SZ
772:002202.SZ
773:002203.SZ
774:002204.SZ
775:002205.SZ
776:002206.SZ
777:002207.SZ
778:002208.SZ
779:002209.SZ
780:002210.SZ
781:002211.SZ
782:002212.SZ
783:002213.SZ
784:002214.SZ
785:002215.SZ
786:002216.SZ
787:002217.SZ
788:002218.SZ
789:002219.SZ
790:002220.SZ
791:002221.SZ
792:002222.SZ
793:002223.SZ
794:002224.SZ
795:002225.SZ
796:002226.SZ
797:002227.SZ
798:002228.SZ
799:002229.SZ
800:002230.SZ
801:002231.SZ
802:002232.SZ
803:002233.SZ
804:002234.SZ
805:002235.SZ
806:002236.SZ
807:002237.SZ
808:002238.SZ
809:002239.SZ
810:002240.SZ
811:002241.SZ
812:002242.SZ
813:002243.SZ
814:002244.SZ
815:002245.SZ
816:002246.SZ
817:002247.SZ
818:002248.SZ
819:002249.SZ
820:002250.SZ
821:002251.SZ
822:002252.SZ
823:002253.SZ
824:002254.SZ
825:002255.SZ
826:002256.SZ
827:002258.SZ
828:002259.SZ
829:002260.SZ
830:002261.SZ
831:002262.SZ
832:002263.SZ
833:002264.SZ
834:002265.SZ
835:002266.SZ
836:002267.SZ
837:002268.SZ
838:002269.SZ
839:002270.SZ
840:002271.SZ
841:002272.SZ
842:002273.SZ
843:002274.SZ
844:002275.SZ
845:002276.SZ
846:002277.SZ
847:002278.SZ
848:002279.SZ
849:002280.SZ
850:002281.SZ
851:002282.SZ
852:002283.SZ
853:002284.SZ
854:002285.SZ
855:002286.SZ
856:002287.SZ
857:002288.SZ
858:002289.SZ
859:002290.SZ
860:002291.SZ
861:002292.SZ
862:002293.SZ
863:002294.SZ
864:002295.SZ
865:002296.SZ
866:002297.SZ
867:002298.SZ
868:002299.SZ
869:002300.SZ
870:002301.SZ
871:002302.SZ
872:002303.SZ
873:002304.SZ
874:002305.SZ
875:002306.SZ
876:002307.SZ
877:002308.SZ
878:002309.SZ
879:002310.SZ
880:002311.SZ
881:002312.SZ
882:002313.SZ
883:002314.SZ
884:002315.SZ
885:002316.SZ
886:002317.SZ
887:002318.SZ
888:002319.SZ
889:002320.SZ
890:002321.SZ
891:002322.SZ
892:002323.SZ
893:002324.SZ
894:002325.SZ
895:002326.SZ
896:002327.SZ
897:002328.SZ
898:002329.SZ
899:002330.SZ
900:002331.SZ
901:002332.SZ
902:002333.SZ
903:002334.SZ
904:002335.SZ
905:002336.SZ
906:002337.SZ
907:002338.SZ
908:002339.SZ
909:002340.SZ
910:002341.SZ
911:002342.SZ
912:002343.SZ
913:002344.SZ
914:002345.SZ
915:002346.SZ
916:002347.SZ
917:002348.SZ
918:002349.SZ
919:002350.SZ
920:002351.SZ
921:002352.SZ
922:002353.SZ
923:002354.SZ
924:002355.SZ
925:002356.SZ
926:002357.SZ
927:002358.SZ
928:002359.SZ
929:002360.SZ
930:002361.SZ
931:002362.SZ
932:002363.SZ
933:002364.SZ
934:002365.SZ
935:002366.SZ
936:002367.SZ
937:002368.SZ
938:002369.SZ
939:002370.SZ
940:002371.SZ
941:002372.SZ
942:002373.SZ
943:002374.SZ
944:002375.SZ
945:002376.SZ
946:002377.SZ
947:002378.SZ
948:002379.SZ
949:002380.SZ
950:002381.SZ
951:002382.SZ
952:002383.SZ
953:002384.SZ
954:002385.SZ
955:002386.SZ
956:002387.SZ
957:002388.SZ
958:002389.SZ
959:002390.SZ
960:002391.SZ
961:002392.SZ
962:002393.SZ
963:002394.SZ
964:002395.SZ
965:002396.SZ
966:002397.SZ
967:002398.SZ
968:002399.SZ
969:002400.SZ
970:002401.SZ
971:002402.SZ
972:002403.SZ
973:002404.SZ
974:002405.SZ
975:002406.SZ
976:002407.SZ
977:002408.SZ
978:002409.SZ
979:002410.SZ
980:002411.SZ
981:002412.SZ
982:002413.SZ
983:002414.SZ
984:002415.SZ
985:002416.SZ
986:002417.SZ
987:002418.SZ
988:002419.SZ
989:002420.SZ
990:002421.SZ
991:002422.SZ
992:002423.SZ
993:002424.SZ
994:002425.SZ
995:002426.SZ
996:002427.SZ
997:002428.SZ
998:002429.SZ
999:002430.SZ
1000:002431.SZ
1001:002432.SZ
1002:002433.SZ
1003:002434.SZ
1004:002435.SZ
1005:002436.SZ
1006:002437.SZ
1007:002438.SZ
1008:002439.SZ
1009:002440.SZ
1010:002441.SZ
1011:002442.SZ
1012:002443.SZ
1013:002444.SZ
1014:002445.SZ
1015:002446.SZ
1016:002447.SZ
1017:002448.SZ
1018:002449.SZ
1019:002450.SZ
1020:002451.SZ
1021:002452.SZ
1022:002453.SZ
1023:002454.SZ
1024:002455.SZ
1025:002456.SZ
1026:002457.SZ
1027:002458.SZ
1028:002459.SZ
1029:002460.SZ
1030:002461.SZ
1031:002462.SZ
1032:002463.SZ
1033:002464.SZ
1034:002465.SZ
1035:002466.SZ
1036:002467.SZ
1037:002468.SZ
1038:002469.SZ
1039:002470.SZ
1040:002471.SZ
1041:002472.SZ
1042:002473.SZ
1043:002474.SZ
1044:002475.SZ
1045:002476.SZ
1046:002477.SZ
1047:002478.SZ
1048:002479.SZ
1049:002480.SZ
1050:002481.SZ
1051:002482.SZ
1052:002483.SZ
1053:002484.SZ
1054:002485.SZ
1055:002486.SZ
1056:002487.SZ
1057:002488.SZ
1058:002489.SZ
1059:002490.SZ
1060:002491.SZ
1061:002492.SZ
1062:002493.SZ
1063:002494.SZ
1064:002495.SZ
1065:002496.SZ
1066:002497.SZ
1067:002498.SZ
1068:002499.SZ
1069:002500.SZ
1070:002501.SZ
1071:002502.SZ
1072:002503.SZ
1073:002504.SZ
1074:002505.SZ
1075:002506.SZ
1076:002507.SZ
1077:002508.SZ
1078:002509.SZ
1079:002510.SZ
1080:002511.SZ
1081:002512.SZ
1082:002513.SZ
1083:002514.SZ
1084:002515.SZ
1085:002516.SZ
1086:002517.SZ
1087:002518.SZ
1088:002519.SZ
1089:002520.SZ
1090:002521.SZ
1091:002522.SZ
1092:002523.SZ
1093:002524.SZ
1094:002526.SZ
1095:002527.SZ
1096:002528.SZ
1097:002529.SZ
1098:002530.SZ
1099:002531.SZ
1100:002532.SZ
1101:002533.SZ
1102:002534.SZ
1103:002535.SZ
1104:002536.SZ
1105:002537.SZ
1106:002538.SZ
1107:002539.SZ
1108:002540.SZ
1109:002541.SZ
1110:002542.SZ
1111:002543.SZ
1112:002544.SZ
1113:002545.SZ
1114:002546.SZ
1115:002547.SZ
1116:002548.SZ
1117:002549.SZ
1118:002550.SZ
1119:002551.SZ
1120:002552.SZ
1121:002553.SZ
1122:002554.SZ
1123:002555.SZ
1124:002556.SZ
1125:002557.SZ
1126:002558.SZ
1127:002559.SZ
1128:002560.SZ
1129:002561.SZ
1130:002562.SZ
1131:002563.SZ
1132:002564.SZ
1133:002565.SZ
1134:002566.SZ
1135:002567.SZ
1136:002568.SZ
1137:002569.SZ
1138:002570.SZ
1139:002571.SZ
1140:002572.SZ
1141:002573.SZ
1142:002574.SZ
1143:002575.SZ
1144:002576.SZ
1145:002577.SZ
1146:002578.SZ
1147:002579.SZ
1148:002580.SZ
1149:002581.SZ
1150:002582.SZ
1151:002583.SZ
1152:002584.SZ
1153:002585.SZ
1154:002586.SZ
1155:002587.SZ
1156:002588.SZ
1157:002589.SZ
1158:002590.SZ
1159:002591.SZ
1160:002592.SZ
1161:002593.SZ
1162:002594.SZ
1163:002595.SZ
1164:002596.SZ
1165:002597.SZ
1166:002598.SZ
1167:002599.SZ
1168:002600.SZ
1169:002601.SZ
1170:002602.SZ
1171:002603.SZ
1172:002604.SZ
1173:002605.SZ
1174:002606.SZ
1175:002607.SZ
1176:002608.SZ
1177:002609.SZ
1178:002610.SZ
1179:002611.SZ
1180:002612.SZ
1181:002613.SZ
1182:002614.SZ
1183:002615.SZ
1184:002616.SZ
1185:002617.SZ
1186:002618.SZ
1187:002619.SZ
1188:002620.SZ
1189:002621.SZ
1190:002622.SZ
1191:002623.SZ
1192:002624.SZ
1193:002625.SZ
1194:002626.SZ
1195:002627.SZ
1196:002628.SZ
1197:002629.SZ
1198:002630.SZ
1199:002631.SZ
1200:002632.SZ
1201:002633.SZ
1202:002634.SZ
1203:002635.SZ
1204:002636.SZ
1205:002637.SZ
1206:002638.SZ
1207:002639.SZ
1208:002640.SZ
1209:002641.SZ
1210:002642.SZ
1211:002643.SZ
1212:002644.SZ
1213:002645.SZ
1214:002646.SZ
1215:002647.SZ
1216:002648.SZ
1217:002649.SZ
1218:002650.SZ
1219:002651.SZ
1220:002652.SZ
1221:002653.SZ
1222:002654.SZ
1223:002655.SZ
1224:002656.SZ
1225:002657.SZ
1226:002658.SZ
1227:002659.SZ
1228:002660.SZ
1229:002661.SZ
1230:002662.SZ
1231:002663.SZ
1232:002664.SZ
1233:002665.SZ
1234:002666.SZ
1235:002667.SZ
1236:002668.SZ
1237:002669.SZ
1238:002670.SZ
1239:002671.SZ
1240:002672.SZ
1241:002673.SZ
1242:002674.SZ
1243:002675.SZ
1244:002676.SZ
1245:002677.SZ
1246:002678.SZ
1247:002679.SZ
1248:002680.SZ
1249:002681.SZ
1250:002682.SZ
1251:002683.SZ
1252:002684.SZ
1253:002685.SZ
1254:002686.SZ
1255:002687.SZ
1256:002688.SZ
1257:002689.SZ
1258:002690.SZ
1259:002691.SZ
1260:002692.SZ
1261:002693.SZ
1262:002694.SZ
1263:002695.SZ
1264:002696.SZ
1265:002697.SZ
1266:002698.SZ
1267:002699.SZ
1268:002700.SZ
1269:002701.SZ
1270:002702.SZ
1271:002703.SZ
1272:002705.SZ
1273:002706.SZ
1274:002707.SZ
1275:002708.SZ
1276:002709.SZ
1277:002711.SZ
1278:002712.SZ
1279:002713.SZ
1280:002714.SZ
1281:002715.SZ
1282:002716.SZ
1283:002717.SZ
1284:002718.SZ
1285:002719.SZ
1286:002721.SZ
1287:002722.SZ
1288:002723.SZ
1289:002724.SZ
1290:002725.SZ
1291:002726.SZ
1292:002727.SZ
1293:002728.SZ
1294:002729.SZ
1295:002730.SZ
1296:002731.SZ
1297:002732.SZ
1298:002733.SZ
1299:002734.SZ
1300:002735.SZ
1301:002736.SZ
1302:002737.SZ
1303:002738.SZ
1304:002739.SZ
1305:002740.SZ
1306:002741.SZ
1307:002742.SZ
1308:002743.SZ
1309:002745.SZ
1310:002746.SZ
1311:002747.SZ
1312:002748.SZ
1313:002749.SZ
1314:002750.SZ
1315:002751.SZ
1316:002752.SZ
1317:002753.SZ
1318:002755.SZ
1319:002756.SZ
1320:002757.SZ
1321:002758.SZ
1322:002759.SZ
1323:002760.SZ
1324:002761.SZ
1325:002762.SZ
1326:002763.SZ
1327:002765.SZ
1328:002766.SZ
1329:002767.SZ
1330:002768.SZ
1331:002769.SZ
1332:002770.SZ
1333:002771.SZ
1334:002772.SZ
1335:002773.SZ
1336:002774.SZ
1337:002775.SZ
1338:002776.SZ
1339:002777.SZ
1340:002778.SZ
1341:002779.SZ
1342:002780.SZ
1343:002781.SZ
1344:002782.SZ
1345:002783.SZ
1346:002785.SZ
1347:002786.SZ
1348:002787.SZ
1349:002788.SZ
1350:002789.SZ
1351:002790.SZ
1352:002791.SZ
1353:002792.SZ
1354:002793.SZ
1355:002795.SZ
1356:002796.SZ
1357:002797.SZ
1358:002798.SZ
1359:002799.SZ
1360:002800.SZ
1361:002801.SZ
1362:002802.SZ
1363:002803.SZ
1364:002805.SZ
1365:002806.SZ
1366:002807.SZ
1367:002808.SZ
1368:002809.SZ
1369:002810.SZ
1370:002811.SZ
1371:002812.SZ
1372:002813.SZ
1373:002815.SZ
1374:002816.SZ
1375:002817.SZ
1376:002818.SZ
1377:002819.SZ
1378:002820.SZ
1379:002821.SZ
1380:002822.SZ
1381:002823.SZ
1382:002824.SZ
1383:002825.SZ
1384:002826.SZ
1385:002827.SZ
1386:002828.SZ
1387:002829.SZ
1388:002830.SZ
1389:002831.SZ
1390:002832.SZ
1391:002833.SZ
1392:002835.SZ
1393:002836.SZ
1394:002837.SZ
1395:002838.SZ
1396:002839.SZ
1397:002840.SZ
1398:002841.SZ
1399:002842.SZ

[3669930:MainThread](2025-09-01 17:05:22,398) INFO - qlib.Initialization - [config.py:451] - default_conf: client.
[3669930:MainThread](2025-09-01 17:05:23,552) WARNING - qlib.OpsWrapper - [ops.py:1900] - The custom operator [EMA] will override the qlib default definition
[3669930:MainThread](2025-09-01 17:05:23,553) WARNING - qlib.OpsWrapper - [ops.py:1900] - The custom operator [WMA] will override the qlib default definition
[3669930:MainThread](2025-09-01 17:05:23,555) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[3669930:MainThread](2025-09-01 17:05:23,557) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/home/quant/qlib_data/cn_data')}

今天的日期是: 2025-09-01

[3669930:MainThread](2025-09-01 17:06:06,564) INFO - qlib.timer - [log.py:127] - Time cost: 42.954s | Loading data Done
[3669930:MainThread](2025-09-01 17:06:55,986) INFO - qlib.timer - [log.py:127] - Time cost: 43.989s | RobustZScoreNorm Done
[3669930:MainThread](2025-09-01 17:07:04,461) INFO - qlib.timer - [log.py:127] - Time cost: 8.470s | Fillna Done
[3669930:MainThread](2025-09-01 17:07:13,065) INFO - qlib.timer - [log.py:127] - Time cost: 2.745s | DropnaLabel Done
[3669930:MainThread](2025-09-01 17:07:15,651) INFO - qlib.timer - [log.py:127] - Time cost: 2.583s | CSZScoreNorm Done
[3669930:MainThread](2025-09-01 17:07:15,666) INFO - qlib.timer - [log.py:127] - Time cost: 69.100s | fit & process data Done
[3669930:MainThread](2025-09-01 17:07:15,668) INFO - qlib.timer - [log.py:127] - Time cost: 112.058s | Init data Done
[3669930:MainThread](2025-09-01 17:08:46,786) INFO - qlib.timer - [log.py:127] - Time cost: 60.292s | Loading data Done
[3669930:MainThread](2025-09-01 17:09:48,618) INFO - qlib.timer - [log.py:127] - Time cost: 50.270s | RobustZScoreNorm Done
[3669930:MainThread](2025-09-01 17:09:57,490) INFO - qlib.timer - [log.py:127] - Time cost: 8.868s | Fillna Done
[3669930:MainThread](2025-09-01 17:10:06,584) INFO - qlib.timer - [log.py:127] - Time cost: 2.739s | DropnaLabel Done
[3669930:MainThread](2025-09-01 17:10:09,168) INFO - qlib.timer - [log.py:127] - Time cost: 2.579s | CSZScoreNorm Done
[3669930:MainThread](2025-09-01 17:10:09,184) INFO - qlib.timer - [log.py:127] - Time cost: 82.395s | fit & process data Done
[3669930:MainThread](2025-09-01 17:10:09,185) INFO - qlib.timer - [log.py:127] - Time cost: 142.691s | Init data Done

In [3]:
last_day_scores = get_pred_scores_mix()

ModuleNotFoundError. CatBoostModel are skipped. (optional: maybe installing CatBoostModel can fix it.)
ModuleNotFoundError. XGBModel is skipped(optional: maybe installing xgboost can fix it).

In [4]:
stock_mix_compay = [
    "603235.SH", "600933.SH", "601958.SH", "600258.SH", "603868.SH",
    "601598.SH", "002242.SZ", "688009.SH", "601811.SH", "688389.SH",
    "601108.SH", "605338.SH", "603508.SH", "603708.SH", "601658.SH",
    "601688.SH", "601288.SH", "300682.SZ", "002511.SZ", "000959.SZ",
    "603368.SH", "002056.SZ", "601990.SH", "300606.SZ", "600061.SH",
    "300627.SZ", "002233.SZ", "688378.SH", "600999.SH", "002960.SZ",
    "688352.SH", "600596.SH", "002045.SZ", "002438.SZ", "002390.SZ",
    "603180.SH", "603408.SH", "301102.SZ", "601377.SH", "603309.SH",
    "300193.SZ", "002655.SZ", "600346.SH", "000404.SZ", "300999.SZ",
    "600109.SH", "603317.SH", "603816.SH", "600452.SH", "002673.SZ"
]
valid_codes = [code for code in stock_mix_compay if code in last_day_scores['instrument'].values]
sorted_df = last_day_scores[last_day_scores['instrument'].isin(valid_codes)].sort_values(
    by='score',
    ascending=False
).reset_index(drop=True)
sorted_df

   instrument     score
0   300682.SZ  0.469154
1   601958.SH  0.438707
2   601688.SH  0.398558
3   600061.SH  0.395196
4   600346.SH  0.389598
5   300999.SZ  0.156158
6   601108.SH  0.154008
7   601990.SH  0.148404
8   601377.SH  0.138622
9   688378.SH  0.120117
10  600258.SH  0.108312
11  600109.SH  0.104594
12  601288.SH  0.103693
13  688352.SH  0.103151
14  688009.SH  0.102729
15  600999.SH  0.096593
16  601811.SH  0.095268
17  002233.SZ  0.089231
18  002673.SZ  0.083047
19  002242.SZ  0.074901
20  603868.SH  0.070026
21  603816.SH  0.065634
22  000404.SZ  0.062437
23  603408.SH  0.057560
24  601598.SH  0.056809
25  601658.SH  0.054742
26  002056.SZ  0.053436
27  002511.SZ  0.052260
28  600596.SH  0.051900
29  603368.SH  0.049879
30  603180.SH  0.048742
31  603235.SH  0.046649
32  600933.SH  0.043905
33  300606.SZ  0.042193
34  603317.SH  0.041707
35  002960.SZ  0.037928
36  603508.SH  0.037861
37  603309.SH  0.035430
38  300193.SZ  0.033072
39  603708.SH  0.031922
40  605338.SH  0.029803
41  002438.SZ  0.023809
42  002655.SZ  0.014692
43  000959.SZ  0.007967
44  301102.SZ  0.006364
45  300627.SZ -0.000282
46  600452.SH -0.001304
47  002390.SZ -0.003509
48  002045.SZ -0.005789
49  688389.SH -0.016606

In [7]:
sorted_df[45:]['instrument'].tolist()

['300627.SZ', '600452.SH', '002390.SZ', '002045.SZ', '688389.SH']

In [8]:
top_100 = last_day_scores.sort_values('score', ascending=False).head(100)

# 重置索引（可选，如果希望 instrument 变成列）
top_100 = top_100.reset_index()
filtered_top_100 = top_100[~top_100['instrument'].isin(sorted_df['instrument'])]
filtered_top_100

    index instrument     score
5      63  000776.SZ  0.354944
6    1272  688127.SH  0.349493
7    1382  688627.SH  0.313181
8      20  000408.SZ  0.273690
9     549  300790.SZ  0.261138
..    ...        ...       ...
95    965  601801.SH  0.074475
96    744  600428.SH  0.074337
97   1118  603588.SH  0.074234
98    932  601456.SH  0.073885
99   1201  605077.SH  0.072728

[80 rows x 3 columns]

In [10]:
filtered_top_100['instrument'][:10].tolist()

['000776.SZ',
 '688127.SH',
 '688627.SH',
 '000408.SZ',
 '300790.SZ',
 '600301.SH',
 '000938.SZ',
 '000676.SZ',
 '000977.SZ',
 '600895.SH']

In [16]:
# last_day_scores = get_pred_scores("gru_company", True)
last_day_scores = get_pred_scores("moe_company", True)

In [17]:
stock_codes_xqb01_online = [
    "603566", "603309", "603355", "603368", "601688", "688009",
    "601288", "600061", "601658", "688352", "601168", "600219",
    "601899", "002441", "600597", "603357", "603816", "600299",
    "603866", "601811", "001289", "601333", "001215", "002242",
    "605368", "300219", "688420", "600681", "603043", "000728",
    "601827", "601878", "601801", "002675", "688366", "601598",
    "603515", "603588", "300999", "002088", "000166", "601066",
    "603408", "600004", "601108", "000404", "002344", "603235",
    "002957", "688533"
]
# valid_codes = [code for code in stock_codes_xqb01_online if code in last_day_scores['instrument'].values]
valid_codes = [
    code for code in stock_codes_xqb01_online
    if code in [x[:6] for x in last_day_scores['instrument'].astype(str)]
]
sorted_df = last_day_scores[last_day_scores['instrument'].astype(str).str[:6].isin(valid_codes)].sort_values(
    by='score',
    ascending=True
).reset_index(drop=True)
sorted_df

   instrument     score
0   002344.SZ  0.015808
1   002675.SZ  0.027188
2   603309.SH  0.047715
3   600219.SH  0.047846
4   601168.SH  0.059815
5   601658.SH  0.061172
6   601899.SH  0.065650
7   603566.SH  0.065983
8   605368.SH  0.066257
9   603235.SH  0.068586
10  603368.SH  0.080232
11  002088.SZ  0.087052
12  603357.SH  0.095212
13  601598.SH  0.101157
14  601811.SH  0.101367
15  601333.SH  0.104010
16  688420.SH  0.105137
17  002242.SZ  0.105250
18  001215.SZ  0.117434
19  601801.SH  0.121405
20  603515.SH  0.121918
21  300219.SZ  0.122626
22  688366.SH  0.124166
23  000404.SZ  0.134151
24  603355.SH  0.137444
25  601827.SH  0.138421
26  603408.SH  0.140220
27  002441.SZ  0.143476
28  688009.SH  0.145307
29  688352.SH  0.154595
30  603866.SH  0.160212
31  001289.SZ  0.161334
32  600299.SH  0.161382
33  000166.SZ  0.161687
34  603816.SH  0.169765
35  688533.SH  0.170849
36  603588.SH  0.175865
37  300999.SZ  0.176265
38  601108.SH  0.176824
39  002957.SZ  0.181940
40  601288.SH  0.197608
41  600597.SH  0.198407
42  601878.SH  0.199773
43  600681.SH  0.203930
44  600004.SH  0.206077
45  603043.SH  0.210615
46  601688.SH  0.219906
47  600061.SH  0.226548
48  601066.SH  0.239121
49  000728.SZ  0.244261

In [18]:
sorted_df[45:]['instrument'].tolist()

['603043.SH', '601688.SH', '600061.SH', '601066.SH', '000728.SZ']

In [19]:
top_100 = last_day_scores.sort_values('score', ascending=False).head(100)

# 重置索引（可选，如果希望 instrument 变成列）
top_100 = top_100.reset_index()
filtered_top_100 = top_100[~top_100['instrument'].isin(sorted_df['instrument'])]
filtered_top_100

    index instrument     score
10   1007  601990.SH  0.191742
17    922  601319.SH  0.169688
18    598  301039.SZ  0.169614
19    927  601377.SH  0.168193
20    726  600339.SH  0.167406
..    ...        ...       ...
95    548  300788.SZ  0.111579
96    282  002643.SZ  0.110890
97    938  601601.SH  0.110325
98    116  001872.SZ  0.109855
99    499  300606.SZ  0.109755

[68 rows x 3 columns]

In [20]:
filtered_top_100['instrument'][:10].tolist()

['601990.SH',
 '601319.SH',
 '301039.SZ',
 '601377.SH',
 '600339.SH',
 '001323.SZ',
 '603730.SH',
 '688006.SH',
 '002233.SZ',
 '601019.SH']

In [4]:
folder_path='/home/quant/data_test/csv_data/daily_data'
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

In [2]:
section_code=pd.read_csv("section_codes.csv")

In [3]:
section_code

      000001
0          9
1         21
2         26
3         27
4         28
...      ...
1404  688789
1405  688798
1406  688800
1407  688819
1408  688981

[1409 rows x 1 columns]

In [9]:
code_mapping={}
for code in csv_files:
    if len(code)>14 or code[:1]=='T':
        continue
    first_six=int(code[:6])
    first_nine=code[:9]
    code_mapping[first_six]=first_nine

In [10]:
code_mapping

{603121: '603121.SH',
 600006: '600006.SH',
 600055: '600055.SH',
 603007: '603007.SH',
 873690: '873690.BJ',
 2940: '002940.SZ',
 603466: '603466.SH',
 600189: '600189.SH',
 2658: '002658.SZ',
 688608: '688608.SH',
 505: '000505.SZ',
 301300: '301300.SZ',
 2706: '002706.SZ',
 301348: '301348.SZ',
 600098: '600098.SH',
 2559: '002559.SZ',
 301658: '301658.SZ',
 2250: '002250.SZ',
 301596: '301596.SZ',
 688721: '688721.SH',
 600928: '600928.SH',
 2082: '002082.SZ',
 301479: '301479.SZ',
 300319: '300319.SZ',
 939: '000939.SZ',
 600697: '600697.SH',
 603012: '603012.SH',
 2768: '002768.SZ',
 688235: '688235.SH',
 603239: '603239.SH',
 2324: '002324.SZ',
 2986: '002986.SZ',
 2112: '002112.SZ',
 600251: '600251.SH',
 839792: '839792.BJ',
 833030: '833030.BJ',
 603068: '603068.SH',
 603816: '603816.SH',
 688599: '688599.SH',
 603386: '603386.SH',
 301038: '301038.SZ',
 603877: '603877.SH',
 300997: '300997.SZ',
 1289: '001289.SZ',
 301112: '301112.SZ',
 300514: '300514.SZ',
 600568: '600568.SH',
 2290: '002290.SZ',
 2572: '002572.SZ',
 2853: '002853.SZ',
 838275: '838275.BJ',
 2042: '002042.SZ',
 603031: '603031.SH',
 600960: '600960.SH',
 603373: '603373.SH',
 600616: '600616.SH',
 300337: '300337.SZ',
 300383: '300383.SZ',
 778: '000778.SZ',
 688299: '688299.SH',
 2086: '002086.SZ',
 300905: '300905.SZ',
 827: '000827.SZ',
 688377: '688377.SH',
 603102: '603102.SH',
 402: '000402.SZ',
 688627: '688627.SH',
 300735: '300735.SZ',
 688261: '688261.SH',
 2881: '002881.SZ',
 609: '000609.SZ',
 831: '000831.SZ',
 688269: '688269.SH',
 720: '000720.SZ',
 300797: '300797.SZ',
 2918: '002918.SZ',
 2326: '002326.SZ',
 301255: '301255.SZ',
 603296: '603296.SH',
 300370: '300370.SZ',
 600525: '600525.SH',
 600762: '600762.SH',
 2701: '002701.SZ',
 300394: '300394.SZ',
 300347: '300347.SZ',
 2197: '002197.SZ',
 301408: '301408.SZ',
 552: '000552.SZ',
 603826: '603826.SH',
 301218: '301218.SZ',
 301100: '301100.SZ',
 2386: '002386.SZ',
 603823: '603823.SH',
 920068: '920068.BJ',
 837592: '837592.BJ',
 600557: '600557.SH',
 600456: '600456.SH',
 2932: '002932.SZ',
 2796: '002796.SZ',
 831195: '831195.BJ',
 601918: '601918.SH',
 832885: '832885.BJ',
 600452: '600452.SH',
 603027: '603027.SH',
 688249: '688249.SH',
 600633: '600633.SH',
 300035: '300035.SZ',
 2350: '002350.SZ',
 300682: '300682.SZ',
 688208: '688208.SH',
 601606: '601606.SH',
 600173: '600173.SH',
 603070: '603070.SH',
 2745: '002745.SZ',
 688318: '688318.SH',
 600757: '600757.SH',
 688776: '688776.SH',
 600963: '600963.SH',
 972: '000972.SZ',
 301160: '301160.SZ',
 870976: '870976.BJ',
 688671: '688671.SH',
 300716: '300716.SZ',
 832786: '832786.BJ',
 688561: '688561.SH',
 1283: '001283.SZ',
 600539: '600539.SH',
 600985: '600985.SH',
 752: '000752.SZ',
 603393: '603393.SH',
 2159: '002159.SZ',
 601579: '601579.SH',
 812: '000812.SZ',
 2901: '002901.SZ',
 603011: '603011.SH',
 2400: '002400.SZ',
 300281: '300281.SZ',
 301191: '301191.SZ',
 300021: '300021.SZ',
 688323: '688323.SH',
 605: '000605.SZ',
 300437: '300437.SZ',
 517: '000517.SZ',
 688339: '688339.SH',
 873169: '873169.BJ',
 688819: '688819.SH',
 600393: '600393.SH',
 600065: '600065.SH',
 603118: '603118.SH',
 300238: '300238.SZ',
 600209: '600209.SH',
 601766: '601766.SH',
 870357: '870357.BJ',
 688381: '688381.SH',
 600610: '600610.SH',
 300083: '300083.SZ',
 600860: '600860.SH',
 600783: '600783.SH',
 603183: '603183.SH',
 688125: '688125.SH',
 2955: '002955.SZ',
 300702: '300702.SZ',
 688426: '688426.SH',
 600318: '600318.SH',
 601939: '601939.SH',
 600216: '600216.SH',
 300368: '300368.SZ',
 688012: '688012.SH',
 2756: '002756.SZ',
 600587: '600587.SH',
 300657: '300657.SZ',
 2841: '002841.SZ',
 301289: '301289.SZ',
 32: '000032.SZ',
 2943: '002943.SZ',
 688400: '688400.SH',
 2609: '002609.SZ',
 2131: '002131.SZ',
 2325: '002325.SZ',
 688172: '688172.SH',
 603499: '603499.SH',
 2962: '002962.SZ',
 601005: '601005.SH',
 688387: '688387.SH',
 603986: '603986.SH',
 300042: '300042.SZ',
 300086: '300086.SZ',
 831167: '831167.BJ',
 688409: '688409.SH',
 300073: '300073.SZ',
 603609: '603609.SH',
 603331: '603331.SH',
 300630: '300630.SZ',
 836: '000836.SZ',
 300894: '300894.SZ',
 600387: '600387.SH',
 603843: '603843.SH',
 603477: '603477.SH',
 2401: '002401.SZ',
 300174: '300174.SZ',
 2513: '002513.SZ',
 300671: '300671.SZ',
 688648: '688648.SH',
 688677: '688677.SH',
 688368: '688368.SH',
 603889: '603889.SH',
 601211: '601211.SH',
 603220: '603220.SH',
 2765: '002765.SZ',
 600162: '600162.SH',
 600605: '600605.SH',
 2284: '002284.SZ',
 2521: '002521.SZ',
 603806: '603806.SH',
 301013: '301013.SZ',
 300663: '300663.SZ',
 949: '000949.SZ',
 301372: '301372.SZ',
 1400: '001400.SZ',
 301225: '301225.SZ',
 2888: '002888.SZ',
 600321: '600321.SH',
 785: '000785.SZ',
 830839: '830839.BJ',
 995: '000995.SZ',
 300170: '300170.SZ',
 2923: '002923.SZ',
 802: '000802.SZ',
 2084: '002084.SZ',
 2148: '002148.SZ',
 600141: '600141.SH',
 2693: '002693.SZ',
 603238: '603238.SH',
 300398: '300398.SZ',
 600259: '600259.SH',
 2317: '002317.SZ',
 300100: '300100.SZ',
 2515: '002515.SZ',
 1218: '001218.SZ',
 300817: '300817.SZ',
 836675: '836675.BJ',
 600775: '600775.SH',
 2387: '002387.SZ',
 5: '000005.SZ',
 600679: '600679.SH',
 603117: '603117.SH',
 603885: '603885.SH',
 688210: '688210.SH',
 300153: '300153.SZ',
 600320: '600320.SH',
 688116: '688116.SH',
 300937: '300937.SZ',
 834770: '834770.BJ',
 603256: '603256.SH',
 301501: '301501.SZ',
 600705: '600705.SH',
 688443: '688443.SH',
 600312: '600312.SH',
 603333: '603333.SH',
 600020: '600020.SH',
 300375: '300375.SZ',
 300687: '300687.SZ',
 600131: '600131.SH',
 2227: '002227.SZ',
 882: '000882.SZ',
 601117: '601117.SH',
 300936: '300936.SZ',
 688297: '688297.SH',
 2497: '002497.SZ',
 2652: '002652.SZ',
 688505: '688505.SH',
 600360: '600360.SH',
 920056: '920056.BJ',
 2293: '002293.SZ',
 2190: '002190.SZ',
 688019: '688019.SH',
 603132: '603132.SH',
 688569: '688569.SH',
 2898: '002898.SZ',
 601881: '601881.SH',
 300243: '300243.SZ',
 600136: '600136.SH',
 300972: '300972.SZ',
 688660: '688660.SH',
 300008: '300008.SZ',
 600467: '600467.SH',
 688448: '688448.SH',
 688115: '688115.SH',
 603912: '603912.SH',
 688237: '688237.SH',
 760: '000760.SZ',
 688006: '688006.SH',
 603020: '603020.SH',
 300265: '300265.SZ',
 697: '000697.SZ',
 839725: '839725.BJ',
 601860: '601860.SH',
 600959: '600959.SH',
 2733: '002733.SZ',
 688097: '688097.SH',
 603439: '603439.SH',
 301528: '301528.SZ',
 600936: '600936.SH',
 300477: '300477.SZ',
 603004: '603004.SH',
 300763: '300763.SZ',
 832000: '832000.BJ',
 301557: '301557.SZ',
 2351: '002351.SZ',
 1326: '001326.SZ',
 2383: '002383.SZ',
 600388: '600388.SH',
 688486: '688486.SH',
 603097: '603097.SH',
 301219: '301219.SZ',
 300515: '300515.SZ',
 600680: '600680.SH',
 300595: '300595.SZ',
 600284: '600284.SH',
 301448: '301448.SZ',
 301088: '301088.SZ',
 603815: '603815.SH',
 2486: '002486.SZ',
 2603: '002603.SZ',
 3008: '003008.SZ',
 605033: '605033.SH',
 603721: '603721.SH',
 605337: '605337.SH',
 301192: '301192.SZ',
 837006: '837006.BJ',
 688052: '688052.SH',
 300955: '300955.SZ',
 600462: '600462.SH',
 895: '000895.SZ',
 2798: '002798.SZ',
 301508: '301508.SZ',
 2128: '002128.SZ',
 603518: '603518.SH',
 601956: '601956.SH',
 600721: '600721.SH',
 2469: '002469.SZ',
 1234: '001234.SZ',
 603755: '603755.SH',
 689009: '689009.SH',
 2457: '002457.SZ',
 603190: '603190.SH',
 2479: '002479.SZ',
 300921: '300921.SZ',
 300071: '300071.SZ',
 301051: '301051.SZ',
 2877: '002877.SZ',
 301020: '301020.SZ',
 2615: '002615.SZ',
 832149: '832149.BJ',
 300002: '300002.SZ',
 600699: '600699.SH',
 601106: '601106.SH',
 300430: '300430.SZ',
 300101: '300101.SZ',
 2248: '002248.SZ',
 603400: '603400.SH',
 688479: '688479.SH',
 837046: '837046.BJ',
 688146: '688146.SH',
 603557: '603557.SH',
 600227: '600227.SH',
 688182: '688182.SH',
 2896: '002896.SZ',
 1209: '001209.SZ',
 600536: '600536.SH',
 300866: '300866.SZ',
 600343: '600343.SH',
 2691: '002691.SZ',
 831961: '831961.BJ',
 688066: '688066.SH',
 600505: '600505.SH',
 301515: '301515.SZ',
 601010: '601010.SH',
 24: '000024.SZ',
 301180: '301180.SZ',
 301128: '301128.SZ',
 300256: '300256.SZ',
 300980: '300980.SZ',
 540: '000540.SZ',
 2544: '002544.SZ',
 301377: '301377.SZ',
 301291: '301291.SZ',
 2946: '002946.SZ',
 600325: '600325.SH',
 993: '000993.SZ',
 600901: '600901.SH',
 600528: '600528.SH',
 915: '000915.SZ',
 300625: '300625.SZ',
 300743: '300743.SZ',
 601107: '601107.SH',
 639: '000639.SZ',
 300199: '300199.SZ',
 2126: '002126.SZ',
 2618: '002618.SZ',
 688150: '688150.SH',
 300777: '300777.SZ',
 2610: '002610.SZ',
 603516: '603516.SH',
 150: '000150.SZ',
 300810: '300810.SZ',
 2420: '002420.SZ',
 2102: '002102.SZ',
 605376: '605376.SH',
 601158: '601158.SH',
 600403: '600403.SH',
 600614: '600614.SH',
 2722: '002722.SZ',
 832278: '832278.BJ',
 603022: '603022.SH',
 90: '000090.SZ',
 600856: '600856.SH',
 688329: '688329.SH',
 601187: '601187.SH',
 2199: '002199.SZ',
 832651: '832651.BJ',
 419: '000419.SZ',
 600891: '600891.SH',
 300935: '300935.SZ',
 2545: '002545.SZ',
 601375: '601375.SH',
 600570: '600570.SH',
 338: '000338.SZ',
 301586: '301586.SZ',
 603662: '603662.SH',
 603656: '603656.SH',
 601059: '601059.SH',
 2759: '002759.SZ',
 2911: '002911.SZ',
 2136: '002136.SZ',
 838: '000838.SZ',
 300307: '300307.SZ',
 830946: '830946.BJ',
 688680: '688680.SH',
 600686: '600686.SH',
 2327: '002327.SZ',
 2707: '002707.SZ',
 600338: '600338.SH',
 600758: '600758.SH',
 1373: '001373.SZ',
 603773: '603773.SH',
 2789: '002789.SZ',
 688449: '688449.SH',
 300665: '300665.SZ',
 300354: '300354.SZ',
 839719: '839719.BJ',
 300188: '300188.SZ',
 2219: '002219.SZ',
 601199: '601199.SH',
 2802: '002802.SZ',
 912: '000912.SZ',
 2344: '002344.SZ',
 688408: '688408.SH',
 836504: '836504.BJ',
 2299: '002299.SZ',
 2104: '002104.SZ',
 301499: '301499.SZ',
 688385: '688385.SH',
 600270: '600270.SH',
 300455: '300455.SZ',
 2009: '002009.SZ',
 600622: '600622.SH',
 603001: '603001.SH',
 300011: '300011.SZ',
 600749: '600749.SH',
 688691: '688691.SH',
 26: '000026.SZ',
 753: '000753.SZ',
 605499: '605499.SH',
 603237: '603237.SH',
 1318: '001318.SZ',
 301323: '301323.SZ',
 300968: '300968.SZ',
 2337: '002337.SZ',
 605158: '605158.SH',
 300607: '300607.SZ',
 600740: '600740.SH',
 1268: '001268.SZ',
 300214: '300214.SZ',
 601101: '601101.SH',
 688247: '688247.SH',
 2005: '002005.SZ',
 300137: '300137.SZ',
 300241: '300241.SZ',
 2499: '002499.SZ',
 2417: '002417.SZ',
 832110: '832110.BJ',
 600577: '600577.SH',
 834639: '834639.BJ',
 603966: '603966.SH',
 600007: '600007.SH',
 2343: '002343.SZ',
 830879: '830879.BJ',
 301275: '301275.SZ',
 1367: '001367.SZ',
 600702: '600702.SH',
 605069: '605069.SH',
 301498: '301498.SZ',
 698: '000698.SZ',
 300412: '300412.SZ',
 600285: '600285.SH',
 300397: '300397.SZ',
 1332: '001332.SZ',
 2871: '002871.SZ',
 719: '000719.SZ',
 2275: '002275.SZ',
 603010: '603010.SH',
 601901: '601901.SH',
 601992: '601992.SH',
 832171: '832171.BJ',
 300334: '300334.SZ',
 300012: '300012.SZ',
 600881: '600881.SH',
 2470: '002470.SZ',
 688496: '688496.SH',
 2359: '002359.SZ',
 600508: '600508.SH',
 300006: '300006.SZ',
 600255: '600255.SH',
 2091: '002091.SZ',
 688219: '688219.SH',
 518: '000518.SZ',
 603337: '603337.SH',
 300538: '300538.SZ',
 515: '000515.SZ',
 301232: '301232.SZ',
 688015: '688015.SH',
 2174: '002174.SZ',
 603322: '603322.SH',
 603211: '603211.SH',
 600400: '600400.SH',
 688177: '688177.SH',
 300047: '300047.SZ',
 301172: '301172.SZ',
 603163: '603163.SH',
 2810: '002810.SZ',
 2556: '002556.SZ',
 601179: '601179.SH',
 836395: '836395.BJ',
 300272: '300272.SZ',
 300708: '300708.SZ',
 600747: '600747.SH',
 835: '000835.SZ',
 600408: '600408.SH',
 600969: '600969.SH',
 603896: '603896.SH',
 600726: '600726.SH',
 816: '000816.SZ',
 300088: '300088.SZ',
 600982: '600982.SH',
 600771: '600771.SH',
 600163: '600163.SH',
 301306: '301306.SZ',
 600817: '600817.SH',
 603703: '603703.SH',
 603689: '603689.SH',
 600357: '600357.SH',
 605058: '605058.SH',
 301487: '301487.SZ',
 600386: '600386.SH',
 2489: '002489.SZ',
 688789: '688789.SH',
 600072: '600072.SH',
 2357: '002357.SZ',
 603069: '603069.SH',
 300411: '300411.SZ',
 300130: '300130.SZ',
 301227: '301227.SZ',
 301368: '301368.SZ',
 300786: '300786.SZ',
 688096: '688096.SH',
 603309: '603309.SH',
 672: '000672.SZ',
 600782: '600782.SH',
 688693: '688693.SH',
 688196: '688196.SH',
 301290: '301290.SZ',
 600938: '600938.SH',
 603833: '603833.SH',
 600272: '600272.SH',
 2422: '002422.SZ',
 600929: '600929.SH',
 600822: '600822.SH',
 688571: '688571.SH',
 601558: '601558.SH',
 601089: '601089.SH',
 2176: '002176.SZ',
 301221: '301221.SZ',
 2740: '002740.SZ',
 600068: '600068.SH',
 2849: '002849.SZ',
 159: '000159.SZ',
 300654: '300654.SZ',
 300813: '300813.SZ',
 600269: '600269.SH',
 2083: '002083.SZ',
 2039: '002039.SZ',
 603696: '603696.SH',
 718: '000718.SZ',
 2999: '002999.SZ',
 300843: '300843.SZ',
 300189: '300189.SZ',
 300484: '300484.SZ',
 2492: '002492.SZ',
 300926: '300926.SZ',
 750: '000750.SZ',
 2460: '002460.SZ',
 920007: '920007.BJ',
 300489: '300489.SZ',
 2987: '002987.SZ',
 601366: '601366.SH',
 2333: '002333.SZ',
 603619: '603619.SH',
 2758: '002758.SZ',
 600966: '600966.SH',
 769: '000769.SZ',
 830: '000830.SZ',
 2289: '002289.SZ',
 301178: '301178.SZ',
 300676: '300676.SZ',
 300996: '300996.SZ',
 603332: '603332.SH',
 688093: '688093.SH',
 300640: '300640.SZ',
 688981: '688981.SH',
 2514: '002514.SZ',
 522: '000522.SZ',
 18: '000018.SZ',
 600641: '600641.SH',
 300485: '300485.SZ',
 300825: '300825.SZ',
 603116: '603116.SH',
 688690: '688690.SH',
 300053: '300053.SZ',
 600361: '600361.SH',
 605298: '605298.SH',
 300546: '300546.SZ',
 2916: '002916.SZ',
 600419: '600419.SH',
 2120: '002120.SZ',
 3027: '003027.SZ',
 300774: '300774.SZ',
 600547: '600547.SH',
 600650: '600650.SH',
 301207: '301207.SZ',
 300862: '300862.SZ',
 601200: '601200.SH',
 600212: '600212.SH',
 300721: '300721.SZ',
 301137: '301137.SZ',
 600648: '600648.SH',
 600600: '600600.SH',
 601000: '601000.SH',
 600745: '600745.SH',
 301133: '301133.SZ',
 601890: '601890.SH',
 600078: '600078.SH',
 605366: '605366.SH',
 600390: '600390.SH',
 688593: '688593.SH',
 1368: '001368.SZ',
 301568: '301568.SZ',
 600794: '600794.SH',
 548: '000548.SZ',
 603391: '603391.SH',
 2087: '002087.SZ',
 301299: '301299.SZ',
 301458: '301458.SZ',
 2477: '002477.SZ',
 301102: '301102.SZ',
 876: '000876.SZ',
 688036: '688036.SH',
 301006: '301006.SZ',
 300758: '300758.SZ',
 300335: '300335.SZ',
 603377: '603377.SH',
 2160: '002160.SZ',
 688516: '688516.SH',
 301265: '301265.SZ',
 300178: '300178.SZ',
 600888: '600888.SH',
 600069: '600069.SH',
 300409: '300409.SZ',
 20: '000020.SZ',
 615: '000615.SZ',
 601999: '601999.SH',
 688147: '688147.SH',
 2431: '002431.SZ',
 300594: '300594.SZ',
 2186: '002186.SZ',
 2418: '002418.SZ',
 300679: '300679.SZ',
 300678: '300678.SZ',
 300923: '300923.SZ',
 603219: '603219.SH',
 300288: '300288.SZ',
 2447: '002447.SZ',
 300718: '300718.SZ',
 2430: '002430.SZ',
 2384: '002384.SZ',
 600842: '600842.SH',
 2575: '002575.SZ',
 600371: '600371.SH',
 2031: '002031.SZ',
 603003: '603003.SH',
 300323: '300323.SZ',
 688136: '688136.SH',
 2636: '002636.SZ',
 834261: '834261.BJ',
 301109: '301109.SZ',
 688719: '688719.SH',
 688002: '688002.SH',
 671: '000671.SZ',
 688211: '688211.SH',
 300990: '300990.SZ',
 1286: '001286.SZ',
 300219: '300219.SZ',
 300978: '300978.SZ',
 2518: '002518.SZ',
 633: '000633.SZ',
 603567: '603567.SH',
 688665: '688665.SH',
 3041: '003041.SZ',
 688310: '688310.SH',
 688030: '688030.SH',
 301141: '301141.SZ',
 513: '000513.SZ',
 33: '000033.SZ',
 2847: '002847.SZ',
 605305: '605305.SH',
 605128: '605128.SH',
 3000: '003000.SZ',
 600222: '600222.SH',
 605258: '605258.SH',
 300132: '300132.SZ',
 603273: '603273.SH',
 600818: '600818.SH',
 600715: '600715.SH',
 2167: '002167.SZ',
 2583: '002583.SZ',
 2752: '002752.SZ',
 603324: '603324.SH',
 600084: '600084.SH',
 605006: '605006.SH',
 688392: '688392.SH',
 688513: '688513.SH',
 300007: '300007.SZ',
 300845: '300845.SZ',
 873703: '873703.BJ',
 300182: '300182.SZ',
 300775: '300775.SZ',
 600597: '600597.SH',
 1298: '001298.SZ',
 836717: '836717.BJ',
 603803: '603803.SH',
 301129: '301129.SZ',
 2292: '002292.SZ',
 301083: '301083.SZ',
 1358: '001358.SZ',
 2792: '002792.SZ',
 2170: '002170.SZ',
 2657: '002657.SZ',
 600236: '600236.SH',
 601636: '601636.SH',
 688248: '688248.SH',
 603922: '603922.SH',
 831396: '831396.BJ',
 2210: '002210.SZ',
 300659: '300659.SZ',
 2340: '002340.SZ',
 688069: '688069.SH',
 2193: '002193.SZ',
 600: '000600.SZ',
 605098: '605098.SH',
 836807: '836807.BJ',
 300133: '300133.SZ',
 2538: '002538.SZ',
 601231: '601231.SH',
 300977: '300977.SZ',
 833509: '833509.BJ',
 601865: '601865.SH',
 603085: '603085.SH',
 600735: '600735.SH',
 603288: '603288.SH',
 300720: '300720.SZ',
 601858: '601858.SH',
 300890: '300890.SZ',
 301587: '301587.SZ',
 2109: '002109.SZ',
 300286: '300286.SZ',
 600750: '600750.SH',
 2669: '002669.SZ',
 300911: '300911.SZ',
 688031: '688031.SH',
 688257: '688257.SH',
 688533: '688533.SH',
 300282: '300282.SZ',
 2453: '002453.SZ',
 600090: '600090.SH',
 688005: '688005.SH',
 603345: '603345.SH',
 300971: '300971.SZ',
 301011: '301011.SZ',
 301606: '301606.SZ',
 300795: '300795.SZ',
 300793: '300793.SZ',
 872808: '872808.BJ',
 881: '000881.SZ',
 603344: '603344.SH',
 37: '000037.SZ',
 2928: '002928.SZ',
 301096: '301096.SZ',
 2546: '002546.SZ',
 301183: '301183.SZ',
 688616: '688616.SH',
 600368: '600368.SH',
 301198: '301198.SZ',
 300028: '300028.SZ',
 300745: '300745.SZ',
 600383: '600383.SH',
 300121: '300121.SZ',
 300751: '300751.SZ',
 301288: '301288.SZ',
 2259: '002259.SZ',
 301: '000301.SZ',
 600099: '600099.SH',
 301533: '301533.SZ',
 300719: '300719.SZ',
 601016: '601016.SH',
 603982: '603982.SH',
 300661: '300661.SZ',
 593: '000593.SZ',
 2362: '002362.SZ',
 688778: '688778.SH',
 521: '000521.SZ',
 401: '000401.SZ',
 600037: '600037.SH',
 600290: '600290.SH',
 300470: '300470.SZ',
 2779: '002779.SZ',
 300050: '300050.SZ',
 958: '000958.SZ',
 603738: '603738.SH',
 536: '000536.SZ',
 603580: '603580.SH',
 600170: '600170.SH',
 300030: '300030.SZ',
 596: '000596.SZ',
 600420: '600420.SH',
 688189: '688189.SH',
 2508: '002508.SZ',
 603895: '603895.SH',
 600675: '600675.SH',
 601369: '601369.SH',
 688499: '688499.SH',
 688309: '688309.SH',
 737: '000737.SZ',
 872925: '872925.BJ',
 601666: '601666.SH',
 300457: '300457.SZ',
 12: '000012.SZ',
 603107: '603107.SH',
 605086: '605086.SH',
 603196: '603196.SH',
 300200: '300200.SZ',
 300168: '300168.SZ',
 2255: '002255.SZ',
 600665: '600665.SH',
 301098: '301098.SZ',
 301595: '301595.SZ',
 688357: '688357.SH',
 300586: '300586.SZ',
 2554: '002554.SZ',
 873833: '873833.BJ',
 835179: '835179.BJ',
 666: '000666.SZ',
 2015: '002015.SZ',
 600375: '600375.SH',
 2141: '002141.SZ',
 600243: '600243.SH',
 600355: '600355.SH',
 838971: '838971.BJ',
 603072: '603072.SH',
 600667: '600667.SH',
 600058: '600058.SH',
 2306: '002306.SZ',
 1277: '001277.SZ',
 838701: '838701.BJ',
 603335: '603335.SH',
 688386: '688386.SH',
 603218: '603218.SH',
 605588: '605588.SH',
 300854: '300854.SZ',
 2969: '002969.SZ',
 300789: '300789.SZ',
 300367: '300367.SZ',
 300278: '300278.SZ',
 1300: '001300.SZ',
 300085: '300085.SZ',
 300628: '300628.SZ',
 601083: '601083.SH',
 2202: '002202.SZ',
 787: '000787.SZ',
 2240: '002240.SZ',
 300820: '300820.SZ',
 3013: '003013.SZ',
 300097: '300097.SZ',
 2564: '002564.SZ',
 631: '000631.SZ',
 1308: '001308.SZ',
 600234: '600234.SH',
 595: '000595.SZ',
 600809: '600809.SH',
 2320: '002320.SZ',
 600855: '600855.SH',
 2668: '002668.SZ',
 601788: '601788.SH',
 600927: '600927.SH',
 603299: '603299.SH',
 586: '000586.SZ',
 603387: '603387.SH',
 301285: '301285.SZ',
 688579: '688579.SH',
 663: '000663.SZ',
 688800: '688800.SH',
 603108: '603108.SH',
 2523: '002523.SZ',
 688391: '688391.SH',
 408: '000408.SZ',
 300068: '300068.SZ',
 2301: '002301.SZ',
 600537: '600537.SH',
 300807: '300807.SZ',

In [11]:
section_code['stockcode']=section_code['000001'].map(code_mapping)

In [13]:
section_code['stockcode'].to_csv("/home/quant/zc/QuantBacktester_60/input/section_codes1.csv",index=False)